### ISSUE TITLE
Dev Site v6.0.0 proposed changes

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#153]
# Proposed changes

## Non passive changes
- [ ] Dependencies updates
- [ ] Remove xfc dependency: https://github.com/cerner/terra-dev-site/issues/158
- [ ] Remove hash router
- [ ] Remove the option to hide a navigation tab
- [ ] Remove theme imports option
- [ ] Remove wdio refresh: https://github.com/cerner/terra-dev-site/issues/136
- [ ] Remove Theming Plugin: https://github.com/cerner/terra-dev-site/issues/159
- [ ] Remove extensions config
- [ ] Consume New navigation 

### Dependencies updates
Move webpack (and webpack related) and terra-toolkit dependencies to be peer dependencies.
This will decouple terra-dev-site from installing webpack. The webpack version should be set by the consumer.

### Remove xfc dependency
See: https://github.com/cerner/terra-dev-site/issues/158

### Remove hash router
By switching to the browser router we can enable hash links to documentation. Webpack-dev-server supports this by using the historyApiFallback parameter. tt-serve and gh-pages can support this behavior by exploiting the 404.html file that is returned when a file is not found. This file can redirect to index.html and update the history state.

### Remove the option to hide a navigation tab
This was always a little weird. We wanted to hide the tab for terra-ui and have access to it for sites with tests. It causes some discoverability issues and we decided it's best if we just show the tab.

### Remove theme imports option
The need for this option has been removed with the aggregate themes project.

### Remove wdio refresh
By far the most disruptive change. See: https://github.com/cerner/terra-dev-site/issues/136

### Remove Theming Plugin
This plugin is unused. See: https://github.com/cerner/terra-dev-site/issues/159

### Remove extensions config
The new navigation has a tighter definition of extensions and the github link no longer makes sense. We may keep the link as a custom item in utilities.

### Consume New navigation
Latest and greatest.

## Blockers
- [ ] navigation: https://github.com/cerner/terra-framework/issues/445
- [ ] terra-toolkit v5: https://github.com/cerner/terra-toolkit/issues/262
- [x] headHtml: https://github.com/cerner/terra-dev-site/pull/152

**Comment by mjhenkes** [comment]
Terra dev site v5 will be a dependencies upgrade in concert with terra-toolkit v5
